# Constants
BATTLE_SCREEN = 'images/battle_screen.png'
BATTLE_ALREADY_SCREEN = 'images/battle_already_screen.png'
VERSUS_SCREEN = 'images/versus_screen.png'
RANDOM_MATCH_SCREEN = 'images/random_match_screen.png'
BATTLE_BUTTON = 'images/battle_button.png'
MATCH_MENU_BUTTON = 'images/match_menu_button.png'
CONCEDE_BUTTON = 'images/concede_button.png'
CONCEDE_ACCEPT_BUTTON = 'images/concede_accept_button.png'
TAP_TO_PROCEED_BUTTON = 'images/tap_to_proceed_button.png'
NEXT_BUTTON = 'images/next_button.png'
THANKS_BUTTON = 'images/thanks_button.png'
CROSS_BUTTON = 'images/cross_button.png'
TIME_LIMIT_INDICATOR = 'images/time_limit_indicator.png'
GOING_FIRST_INDICATOR = 'images/going_first_indicator.png'
GOING_SECOND_INDICATOR = 'images/going_second_indicator.png'