import cv2
from constants import (
    BATTLE_SCREEN,
    BATTLE_ALREADY_SCREEN,
    VERSUS_SCREEN,
    RANDOM_MATCH_SCREEN,
    BATTLE_BUTTON,
    MATCH_MENU_BUTTON,
    CONCEDE_BUTTON,
    CONCEDE_ACCEPT_BUTTON,
    TAP_TO_PROCEED_BUTTON,
    NEXT_BUTTON,
    THANKS_BUTTON,
    CROSS_BUTTON,
    TIME_LIMIT_INDICATOR,
    GOING_FIRST_INDICATOR,
    GOING_SECOND_INDICATOR
)

def load_template_images():
    return {
        "BATTLE_SCREEN": cv2.imread(BATTLE_SCREEN),
        "BATTLE_ALREADY_SCREEN": cv2.imread(BATTLE_ALREADY_SCREEN),
        "VERSUS_SCREEN": cv2.imread(VERSUS_SCREEN),
        "RANDOM_MATCH_SCREEN": cv2.imread(RANDOM_MATCH_SCREEN),
        "BATTLE_BUTTON": cv2.imread(BATTLE_BUTTON),
        "MATCH_MENU_BUTTON": cv2.imread(MATCH_MENU_BUTTON),
        "CONCEDE_BUTTON": cv2.imread(CONCEDE_BUTTON),
        "CONCEDE_ACCEPT_BUTTON": cv2.imread(CONCEDE_ACCEPT_BUTTON),
        "TAP_TO_PROCEED_BUTTON": cv2.imread(TAP_TO_PROCEED_BUTTON),
        "NEXT_BUTTON": cv2.imread(NEXT_BUTTON),
        "THANKS_BUTTON": cv2.imread(THANKS_BUTTON),
        "CROSS_BUTTON": cv2.imread(CROSS_BUTTON),
        "TIME_LIMIT_INDICATOR": cv2.imread(TIME_LIMIT_INDICATOR),
        "GOING_FIRST_INDICATOR": cv2.imread(GOING_FIRST_INDICATOR),
        "GOING_SECOND_INDICATOR": cv2.imread(GOING_SECOND_INDICATOR)
    }